### ISSUE TITLE
本地推理，相同图片ocr执行多次，每次识别结果不同

### ISSUE THREAD

**Issue by Sandwichzhao** [Ucas-HaoranWei/Vary#59]
python vary/demo/run_qwen_vary.py  --model-name /myModel/   --image-file ocr_img/end.png

**Comment by Sandwichzhao** [comment]
图片链接 https://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E7%89%87%E5%B0%BE%E5%88%B6%E4%BD%9C%E4%BA%BA%E5%91%98%E5%90%8D%E5%8D%95%20%E5%9B%BE%E7%89%87&hs=0&pn=1&spn=0&di=7264239678495129601&pi=0&rn=1&tn=baiduimagedetail&is=0%2C0&ie=utf-8&oe=utf-8&cl=2&lm=-1&cs=1863237620%2C2447915323&os=4120087763%2C2981141860&simid=1863237620%2C2447915323&adpicid=0&lpn=0&ln=30&fr=ala&fm=&sme=&cg=&bdtype=0&oriquery=%E7%89%87%E5%B0%BE%E5%88%B6%E4%BD%9C%E4%BA%BA%E5%91%98%E5%90%8D%E5%8D%95%20%E5%9B%BE%E7%89%87&objurl=https%3A%2F%2Fpic3.zhimg.com%2F50%2Fv2-c763917d94c9d6adf35858a4e7ded899_hd.jpg&fromurl=ippr_z2C%24qAzdH3FAzdH3Foood_z%26e3Bziti7_z%26e3Bv54AzdH3Fq7jfpt5gAzdH3Fn9nl80l09&gsm=&islist=&querylist=&dyTabStr=MCwzLDEsMiw2LDQsNSw3LDgsOQ%3D%3D

**Comment by Ucas-HaoranWei** [comment]
roll出来结果不同很正常，除非你sample=False
