### ISSUE TITLE
关于论文中Vary-tiny和Vary-base训练方式有些疑惑

### ISSUE THREAD

**Issue by shihuai** [Ucas-HaoranWei/Vary#6]
感谢你们将如此好的工作分享给大家。我对你们的论文也十分感兴趣，关于论文中 Vary-tiny 和 Vary-base 的训练方式还有一些疑惑的地方，想向你们请教一下。
1. Vary-tiny
关于 Vary-tiny 部分，论文中用了文档、图表、自然图像三种数据进行训练，训练过程中，自然图像是预测 "It’s an image of nature"，文档类型是直接预测文档中的所有文字信息，图表类型是预测图标对应的 python-dict。不知道这部分理解有没有问题。

2. Vary-base
Vary-base 训练包含预训练和微调两个阶段，预训练直接使用的是来自 LAION-COCO 数据集的文本图像对。但在微调阶段论文中提到使用了 LLaVA-80k，不知道在 3.2.2 和 3.3.2 节中渲染的文档数据和图表数据是否也会参与微调，还是在用 LLaVA-80k 微调好的模型基础上，用渲染的数据再根据特定任务进行微调？

**Comment by Ucas-HaoranWei** [comment]
感谢关注：
1.理解是正确的
2.预训练理解正确，微调阶段没有使用3.2.2和3.3.2渲染的数据，只使用了通用数据，因为我们发现只用通用数据依旧可以保持预训练的能力。

**Comment by shihuai** [comment]
嗯，了解。谢谢解答。

**Comment by zxy1728** [comment]
> 感谢关注： 1.理解是正确的 2.预训练理解正确，微调阶段没有使用3.2.2和3.3.2渲染的数据，只使用了通用数据，因为我们发现只用通用数据依旧可以保持预训练的能力。

请问训练好的vary-tiny可以直接用来对图片进行编码吗
