### ISSUE TITLE
训练时出现tokenizer mismatch的情况，对应代码如下，不是每个数据都出现，有什么解决方法么？从代码没看出什么问题

### ISSUE THREAD

**Issue by samaritan1998** [Ucas-HaoranWei/Vary#63]
for conversation, target in zip(conversations, targets):
            total_len = int(target.ne(self.tokenizer.pad_token_id).sum())

            rounds = conversation.split(conv.sep)
            re_rounds = [conv.sep.join(rounds[:3])] # system + user + gpt
            for conv_idx in range(3, len(rounds), 2):
                re_rounds.append(conv.sep.join(rounds[conv_idx:conv_idx+2]))    # user + gpt
            cur_len = 0
            target[:cur_len] = IGNORE_INDEX
            for i, rou in enumerate(re_rounds):
                if rou == "":
                    break

                parts = rou.split(sep)
                if len(parts) != 2:
                    break
                parts[0] += sep
                round_len = len(self.tokenizer(rou).input_ids) + len(self.tokenizer(conv.sep).input_ids)

                instruction_len = len(self.tokenizer(parts[0]).input_ids)
                target[cur_len : cur_len + instruction_len] = IGNORE_INDEX

                cur_len += round_len
            target[cur_len:] = IGNORE_INDEX

            if cur_len < self.tokenizer.model_max_length:
                if cur_len != total_len:
                    target[:] = IGNORE_INDEX
                    print(
                        f"WARNING: tokenization mismatch: {cur_len} vs. {total_len}."
                        f" (ignored)"
                    )

**Comment by Ucas-HaoranWei** [comment]
1.conversation模板是否使用的mpt
2.检查你的数据，超长或者包含special token不

**Comment by samaritan1998** [comment]
找到原因了，是使用的mpt模板，但是value有为空字符的情况，剔除后可以了，感谢
