### ISSUE TITLE
Vary Tiny无法复现，官方代码无法训练

### ISSUE THREAD

**Issue by lucasjinreal** [Ucas-HaoranWei/Vary#89]
之前一直用的llava架构更改，无法复现，想跑一下官方代码看看哪里没有对齐，结果：

![image](https://github.com/Ucas-HaoranWei/Vary/assets/21303438/dc40d637-8501-4e5d-90f8-adf0b3faf814)

遇到了些许问题，作者可以帮忙看看吗？

**Comment by Ucas-HaoranWei** [comment]
当前这套代码是基于内部的名叫“mmgpt”的项目重构的，只测试过inference，不排除train有bug，我有空查一下

**Comment by lucasjinreal** [comment]
社区应该有人提出过训练的问题了，应该是跟max length 和 tokenizer里面某些长度没有对齐导致的，有空麻烦看看怎么才能训起来
